### ISSUE TITLE
Can't run under Windows (vscode)

### ISSUE THREAD

**Issue by gonzas** [shner-elmo/TradeZero_API#3]
Hello again.

I could run your project under linux whitout issues, but I am having dificulties to run under windows trought vscode.
After cloning the repo and setting a enviroment with the IDE, I get this output:

```
PS C:\Users\gonza\Documents\tradezero-api-1>  c:; cd 'c:\Users\gonza\Documents\tradezero-api-1'; & 'c:\Users\gonza\Documents\tradezero-api-1\.venv\Scripts\python.exe' 
'c:\Users\gonza\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '62578' '--' 'c:\Users\gonza\Documents\tradezero-api-1\tradezero_api\tradeZero.py'
last: 1.43, Quantity 100, High: 3.11, Low: 1.51
Traceback (most recent call last):
  File "c:\Users\gonza\Documents\tradezero-api-1\tradezero_api\tradeZero.py", line 21, in <module>
    if (tz.Portfolio.invested(symbol_name)):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonza\Documents\tradezero-api-1\tradezero_api\portfolio.py", line 58, in invested
    data = self.portfolio('dict')
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonza\Documents\tradezero-api-1\tradezero_api\portfolio.py", line 33, in portfolio
    df.columns = [
    ^^^^^^^^^^
  File "c:\Users\gonza\Documents\tradezero-api-1\.venv\Lib\site-packages\pandas\core\generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "c:\Users\gonza\Documents\tradezero-api-1\.venv\Lib\site-packages\pandas\core\generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "c:\Users\gonza\Documents\tradezero-api-1\.venv\Lib\site-packages\pandas\core\internals\managers.py", line 230, in set_axis     
    self._validate_set_axis(axis, new_labels)
  File "c:\Users\gonza\Documents\tradezero-api-1\.venv\Lib\site-packages\pandas\core\internals\base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 11 elements
```

Any clues what to do to resolve this ?

Thanks

**Comment by gonzas** [comment]
I resolved this issue by opening a powershell with administrator rights and pasting this:

`Set-ExecutionPolicy Unrestricted`
